// Program: MyArgs
// ./gen.exe | xargs ./a.exe
// this will use the values generated by gen.exe as argv input for a.exe
#include <iostream>
 
int main(int argc, char *argv[])
{
    std::cout << "There are " << argc << " arguments:\n";
 
    // Loop through each argument and print its number and value
    for (int count{ 0 }; count < argc; ++count)
    {
        std::cout << count << ' ' << argv[count] << '\n';
    }
 
    return 0;
}